name: "Hacktoberfest Labeler"
description: "A Github Action to automate Hacktoberfest"
branding:
  icon: tag
  color: orange

### Action inputs (see also args below)
inputs:
  github_token:
    description: "Github token to use"
    required: true
  edit_label_name:
    description: "The label name to edit"
    required: false
    default: "hacktoberfest"
  edit_label_color:
    description: "The label color"
    required: false
    default: "ffa663"
  edit_label_description:
    description: "The label description"
    required: false
    default: "Good issues for Hacktoberfest"
  filter_label:
    description: "The label to use for filtering issues"
    required: false
    default: "good first issue"
  revert:
    description: "If true the label will be removed instead of added"
    required: false
    default: "0"

runs:
  using: "composite"
  steps:
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.13"

    - run: uv sync
      shell: bash
      working-directory: ${{ github.action_path }}

    - run: |
        uv run hacktoberfest-labeler \
          --github-token '${{ inputs.github_token }}' \
          --filter-label '${{ inputs.filter_label }}' \
          --edit-label-name '${{ inputs.edit_label_name }}' \
          --edit-label-color '${{ inputs.edit_label_color }}' \
          --edit-label-description '${{ inputs.edit_label_description }}' \
          ${{ inputs.revert == '1' && '--revert' || '' }}
      shell: bash
      working-directory: ${{ github.action_path }}
