name: Semantic Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Release
        uses: python-semantic-release/python-semantic-release@v10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Update major and minor tags
      - name: Make minor and major tags
        run: |
          FULL_TAG=$(git describe --tags)
          echo "Full tag: ${FULL_TAG}"
          MINOR=$(echo "${FULL_TAG}" | cut -d'.' -f1-2)
          MAJOR=$(echo "${FULL_TAG}" | cut -d'.' -f1)
          echo "Got minor and major tags: ${MINOR}, ${MAJOR}"
          git tag -f "${MINOR}"
          git tag -f "${MAJOR}"
      - name: Push tags
        run: git push origin HEAD:refs/heads/main --tags --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
