name: Semantic Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Run semantic release:
      # - Update CHANGELOG.md
      # - Update version in code
      # - Create git tag
      # - Create GitHub release
      # - Publish to PyPI
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@v7.33.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}

      # Update major and minor tags
      - name: Make minor and major tags
        run: |
          FULL_TAG=$(git describe --tags)
          echo "Full tag: ${FULL_TAG}"
          MINOR=$(echo "${FULL_TAG}" | cut -d'.' -f1-2)
          MAJOR=$(echo "${FULL_TAG}" | cut -d'.' -f1)
          echo "Got minor and major tags: ${MINOR}, ${MAJOR}"
          git tag "${MINOR}"
          git tag "${MAJOR}"
      - name: Push tags
        run: git push origin HEAD:refs/heads/main --tags --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
